version: '3.8'
services:

  identityserver:
    build:
      context: .
      dockerfile: Identity/IdentityServer/Dockerfile
    ports:
      - 6001:6001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6001
    networks:
      - default

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4