version: '3.8'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
    ports:
        - 8080:8080

  nginx:
    image: nginx:latest
    ports:
        - 1433:1433


networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4