version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Catalog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=server=postgres;port=5432;database=CatalogDB;uid=postgres;password=taya090905;
      - DOCKER_ENV=true
    depends_on:
      - postgres
    ports:
      - 5000:5000
 
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: src/IdentityServer/Identity.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - CatalogApi=http://localhost:5000
    ports:
      - 5001:5001

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/gateway/nginx/default.conf:/etc/gateway/nginx/conf.d/default.conf
      - ./src/Catalog.API/Pictures:/images
    ports:
      - "80:80"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: taya090905
    depends_on:
      - postgres
    ports:
      - 8001:80 

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: taya090905
    ports:
      - 5432:5432
 
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4