// <auto-generated />
using System;
using Catalog.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20240122140344_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Data.Entities.CatalogBrandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CatalogBrand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8198),
                            Title = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8200),
                            Title = "Adidas"
                        });
                });

            modelBuilder.Entity("Catalog.Data.Entities.CatalogItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PictureFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TypeId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("CatalogItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8208),
                            Description = "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with classic details and throwback hoops flair. ",
                            PictureFile = "nike-dunk-low-retro-premium.png",
                            Price = 100m,
                            Quantity = 5,
                            Title = "Nike Dunk Low Retro Premium",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8211),
                            Description = "Created for the hardwood but taken to the streets, the '80s b-ball icon returns with crisp leather and and classic \"Panda\" color blocking.",
                            PictureFile = "nike-dunk-mid.png",
                            Price = 120m,
                            Quantity = 10,
                            Title = "Nike Dunk Mid",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8212),
                            Description = "Meet your new go-to hoodie. Heavyweight fleece feels super soft, and the comfy, relaxed fit will have you reaching for it again and again.",
                            PictureFile = "jordan-flight-fleece.png",
                            Price = 100m,
                            Quantity = 15,
                            Title = "Jordan Flight Fleece",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8214),
                            Description = "These are not just sneakers, but a real symbol of the era. The adidas Forum model appeared in 1984 and won love not only on basketball courts, but also in show business.",
                            PictureFile = "forum-low.png",
                            Price = 110m,
                            Quantity = 6,
                            Title = "Forum Low",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8216),
                            Description = "For your team. For your planet. Created with grassroots football in mind, the Entrada 22 range gives you everything you need to make your game feel and look more beautiful. ",
                            PictureFile = "entrada-22-sweat-hoodie.png",
                            Price = 60m,
                            Quantity = 10,
                            Title = "ENTRADA 22 SWEAT HOODIE",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8219),
                            Description = "Ja Morant became the superstar he is today by repeatedly sinking jumpers on crooked rims, jumping on tractor tires and dribbling through traffic cones in steamy South Carolina summers.",
                            PictureFile = "ja-1.png",
                            Price = 130m,
                            Quantity = 2,
                            Title = "Ja 1",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8220),
                            Description = "Feel unbeatable, from the tee box to the final putt. Inspired by one of the most iconic sneakers of all time, the Air Jordan 1 G is an instant classic on the course. ",
                            PictureFile = "air-jordan-i-high.png",
                            Price = 190m,
                            Quantity = 5,
                            Title = "Air Jordan I High G",
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("Catalog.Data.Entities.CatalogTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CatalogType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8190),
                            Title = "Shoes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 22, 14, 3, 43, 830, DateTimeKind.Utc).AddTicks(8194),
                            Title = "Hoodie"
                        });
                });

            modelBuilder.Entity("Catalog.Data.Entities.CatalogItemEntity", b =>
                {
                    b.HasOne("Catalog.Data.Entities.CatalogBrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Data.Entities.CatalogTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
